name: Release Binary

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          BUILD_TARGET: [release] # refers to a cargo profile
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v4

      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}

      - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo test --profile ${{ matrix.BUILD_TARGET }}

      - name: Publish built binary to GitHub releases
        run: |
          set -e
          cp target/${{ matrix.BUILD_TARGET }}/rws .
          tar -czvf rws-linux-x86_64.tar.gz rws README.md LICENSE
          gh release create v$(date +%s) --generate-notes rws-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
